//
// Created by JavaMan on 2021/10/20.
//

#ifndef SWUFEAUTOREPORTSYSTEMOC_MISUIUTIL_H
#define SWUFEAUTOREPORTSYSTEMOC_MISUIUTIL_H

//#define SCREEN_BOUNDS [UIScreen mainScreen].bounds

#endif //SWUFEAUTOREPORTSYSTEMOC_MISUIUTIL_H
